# main text of home
name: n_stlga
bio: poppin' shells on yer fone

description: poppin' shells on yer fone

# if it's an external image, update below for true
# better with square images
external-image: true
picture: assets/images/fsoc.jpg

resume: false
resume-external: false
resume-url: n-stalgia.github.io/resume.docx

url: https://n-stalgia.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories


twitter: n_stlga
github: n-stalgia
email: sshoreboarder@yahoo.com
cydia: n-stalgia.github.io/cydia
nitotv: n-stalgia.github.io/nitotv
# instagram: 
# youtube: 
# spotify: 
# reddit: 

authors:
    nostalg1a:
        name: n_stlga
        bio: poppin' shells on yer fone
        external-image: true
        picture: assets/images/fsoc.jpg
        twitter: n_stlga
    nostalg1a:
        name: n_stlga
        bio: poppin' shells on yer fone
        external-image: true
        picture: assets/images/fsoc.jpg
        twitter: n_stlga

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

about: true
cydia: true
nitotv: true
blog: true
projects: true


read-time: true

show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

show-author: false

animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
